export const CAMPAIGN_SENDING_REPUTATION_WINDOW_MS = 30 * 24 * 60 * 60 * 1000;

export const CAMPAIGN_SENDING_REPUTATION_MINIMUM_ATTEMPTED_COUNT = 500;

export const CAMPAIGN_MAX_BOUNCE_RATE = 0.05;

export const CAMPAIGN_MAX_COMPLAINT_RATE = 0.003;
